# Non-default settings only; kitty's stock defaults apply to everything else.
font_family      family="CodeNewRoman Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
cursor_trail 1
sync_to_monitor yes
active_border_color #00ff00
inactive_border_color #cccccc
